<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgxq4ax\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgxq4ax/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWgxq4ax.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWgxq4ax\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWgxq4ax\appProdProjectContainer([
    'container.build_hash' => 'Wgxq4ax',
    'container.build_id' => '118c056a',
    'container.build_time' => 1661565896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgxq4ax');
