<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYaujxos\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYaujxos/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYaujxos.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYaujxos\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYaujxos\appDevDebugProjectContainer([
    'container.build_hash' => 'Yaujxos',
    'container.build_id' => '6f90e5c1',
    'container.build_time' => 1661566326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYaujxos');
