<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjl0m6o\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjl0m6o/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXjl0m6o.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXjl0m6o\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXjl0m6o\appDevDebugProjectContainer([
    'container.build_hash' => 'Xjl0m6o',
    'container.build_id' => 'd614ec8e',
    'container.build_time' => 1661571069,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjl0m6o');
